#!/usr/bin/env python3
import pickle
import random
import os

deck = 'flashcards'
if not os.path.exists('decks'):
    os.mkdir('decks')

#Flashcard storage
def save_cards(cards):
    global deck
    with open('decks/%s.pkl' % deck, 'wb') as f:
        pickle.dump(cards, f)

def load_cards():
    global deck
    try:
        with open('decks/%s.pkl' % deck, 'rb') as f:
            return pickle.load(f)
    except FileNotFoundError:
        #First run
        cards = {}
        return cards

def help_menu():
    print("""Available commands:
    [A]ll cards
    [C]reate new card
    [Ch]ange deck
    [D]elete card
    [H]elp menu
    [L]ookup cards
    [M]odify cards
    [S]tart studying with random cards
    [E]xit
    """)

if __name__ == '__main__':
    print("Welcome to flashcards!")
    try:
        cards = load_cards()
        help_menu()
        command = input(" > ").strip().lower() if cards != {} else 'ch'
        while len(command) == 0 or command[0] != 'e':
            if command == '':
                pass
            elif command[0] == 'a':
                print(cards)
            elif command[:2] == 'ch':
                #Change deck
                available = list(map(lambda s: s.replace('.pkl',''),os.listdir('decks')))
                print('Available decks: %s\nEnter name of deck to load it, or create a new deck if it does not yet exist.' % available)
                deck = input(' > ').strip().lower()
                cards = load_cards()
            elif command[0] == 'c':
                #Create new card
                print("To stop creating new cards, leave the front of a card blank.")
                front = input('Enter the front of the card:\n > ')
                while front != '':
                    back = input('Enter the back of the card:\n > ')
                    cards[front]=back
                    print('New card added')
                    front = input('Enter the front of the card:\n > ')
                save_cards(cards)
            elif command[0] == 'd':
                lookup = input('Enter card to delete, or leave empty to return to menu:\n > ')
                if lookup != '':
                    if lookup in cards:
                        del cards[lookup]
                    else:
                        print('Card not found')
            elif command[0] == 'l':
                #Lookup card
                lookup = input('Enter card to search for, or leave empty to return to menu:\n > ')
                while lookup != '':
                    print(lookup,':', cards[lookup] if lookup in cards else 'not found')
                    lookup = input('Enter card to search for, or leave empty to return to menu:\n > ')
            elif command[0] == 'h':
                help_menu()
            elif command[0] == 'm':
                #Modify card
                lookup = input('Enter card to search for, or leave empty to return to menu:\n > ')
                while lookup != '':
                    if lookup in cards:
                        back = input('Currently: %s.\n Please enter a new value for the back, or leave empty to keep as is. \n > ' % cards[lookup])
                    else:
                        print('Card not found. To make this a new card, provide a value for the back; to return to the menu press enter.\n > ')
                    lookup = input('Enter card to search for, or leave empty to return to menu: \n >')
            elif command[0] == 's':
                #Normal study
                if len(cards) == 0:
                    print("You must add flashcards first!")
                else:
                    #Optimisation: no need to recompute
                    options = list(cards.keys())
                    print("You will be presented with a series of flashcards. Guess the back, press enter to see it anyway, or type 'EXIT' to stop.")
                    card = random.choice(options)
                    guess = input('  %s\n > ' % card)
                    while guess != 'EXIT':
                        if guess == '':
                            #Pass
                            print(cards[card])
                            card = random.choice(options)
                            guess = input('  %s\n > ' % card)
                        elif guess.lower() == cards[card].lower():
                            print('Correct!')
                            card = random.choice(options)
                            guess = input('  %s\n > ' % card)
                        else:
                            #Incorrect
                            print('Incorrect, try again :)')
                            guess = input('  %s\n > ' % card)
            #Next command
            command = input(" > ").strip().lower()
    except (EOFError,KeyboardInterrupt):
        #Some user's method for exiting.
        pass
    finally:
        #Exit
        save_cards(cards)
        print("\nSee you later :)\n")
